apiVersion: k3d.io/v1alpha4
kind: Simple
metadata: 
  name: ha

image: rancher/k3s:v1.23.14-k3s1

servers: 3

volumes: # repeatable flags are represented as YAML lists
  - volume: var-lib-rancher-k3s-agent-containerd-0:/var/lib/rancher/k3s/agent/containerd
    nodeFilters:
      - server:0
  - volume: var-lib-rancher-k3s-agent-containerd-1:/var/lib/rancher/k3s/agent/containerd
    nodeFilters:
      - server:1
  - volume: var-lib-rancher-k3s-agent-containerd-2:/var/lib/rancher/k3s/agent/containerd
    nodeFilters:
      - server:2

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

options:
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*